name: dashboard
description: Green Lean Electrics prosumer and manager dashboard

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  fl_chart: ^0.9.2
  pie_chart: ^3.1.1
  async_redux: ^2.7.0
  json_annotation: ^3.0.1
  get_it: ^4.0.1
  shared_preferences: ^0.5.7
  flutter_map: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  json_serializable: ^3.3.0
  logger: ^0.9.1

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  fonts:
    - family: GreenLean
      fonts:
        - asset: fonts/GreenLean.ttf
