name: Build and deploy to Firebase Hosting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup Flutter in beta channel
      uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - name: Download dependencies
      run: flutter pub get
    - name: Build web release
      run: flutter build web --release
    - name: Upload web release as artifact
      uses: actions/upload-artifact@v1
      with:
        name: web-snapshot
        path: build/web
