name: Build and deploy to Firebase Hosting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build web artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup Flutter in beta channel
      uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - name: Enable web support  
      run: flutter config --enable-web
    - name: Download dependencies
      run: flutter pub get
    - name: Build web release
      run: flutter build web --release
    - name: Upload web release as artifact
      uses: actions/upload-artifact@v1
      with:
        name: public
        path: build/web
  
  deploy:
    name: Deploy to Firebase
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@v1
      with:
        name: public
        path: firebase/public
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_PATH: firebase
